export EDITOR=vim
cat <<'MSG'


                         db        88888888ba    ,ad8888ba,
                        d88b       88      "8b  d8"'    `"8b
                       d8'`8b      88      ,8P d8'
                      d8'  `8b     88aaaaaa8P' 88
                     d8YaaaaY8b    88""""88'   88
                    d8""""""""8b   88    `8b   Y8,
                   d8'        `8b  88     `8b   Y8a.    .a8P
                  d8'          `8b 88      `8b   `"Y8888Y"'

             ad88888ba
            d8"     "8b              ,d
            Y8,                      88
            `Y8aaaaa,    ,adPPYba, MM88MMM 88       88 8b,dPPYba,
              `"""""8b, a8P_____88   88    88       88 88P'    "8a
                    `8b 8PP"""""""   88    88       88 88       d8
            Y8a     a8P "8b,   ,aa   88,   "8a,   ,a88 88b,   ,a8"
             "Y88888P"   `"Ybbd8"'   "Y888  `"YbbdP'Y8 88`YbbdP"'
                                                       88
                                                       88

Welcome to ARC Setup, a utility script to provision a Actions Runner Controller
(ARC) instance to a new Azure Kubernertes Cluster (AKS).

The core entrypoint is the `./setup.sh` script in the current directory. It
will guide you through the process of:
- Installing a GitHub App to your Organization (on either GHES/github.com)
- Provisioning a new AKS Cluster to host your instance ARC and the self-hoster
  runners it will manage
- Provisioning a TLS enabled webhook ingress to autoscale your self-hosted
  runners.

This script will ask you to authenticate via the `az` (Azure) and `gh` (GitHub)
CLIs.

This script will provision resources to your specified Azure Subscription under
a new Resource Group.

All provisioning of resources to Azure and eventually to your newly provisioned
cluster is managed by `terraform`. You can inspect the relevant files:

- azure.tf:  Provisions a new Resource Group and AKS Cluster

- helm.tf:   Provisions actions-runner-controller, ingress-nginx, and
             cert-manager

- k8.tf:     Provisions a RunnerDeployment, RunnerAutoscaler, ClusterIssuer, and
             Ingress

- input.tf:  Describes the input variables for the terraform environments,
             these will be injected via a `terraform.tfvars.json` file which is
             generated by `arc-setup`.

- output.tf: Contains outputs for terraform, currently only the `webhook_url`
             which will be the host where the ARC webhook server will be
             accessible.

The `arc-setup` command is responsible for generating a `terraform.tfvars.json`
file which contains the variables required to provision the resources to your
account. As part of this it will create a new GitHub App using the GitHub App
Manifest Flow implemented at https://gamf.bissy.io.

To get started, run `./setup.sh`.
MSG
